from typing import List, Optional
from pydantic import BaseModel, Field
from enum import Enum
from sqlalchemy import Column, String
from sqlalchemy.orm import declarative_base
import logging

# Initialize SQLAlchemy Declarative Base for ORM models

Base = declarative_base()

# Configure module-level logger (useful if logging is needed later)

logger = logging.getLogger(__name__)


class BiomedicalEntity(BaseModel):
    """
    Pydantic model representing a biomedical entity (e.g., gene, protein, disease, drug).
    Includes optional UMLS mapping and a flag indicating whether the entity was LLM-generated.
    """
    # Human-readable name (canonical or as extracted)
    name: str = Field(..., description="The name of the biomedical entity, such as a gene name, drug name, or disease name.")
    # Optional persistent identifier (e.g., Neo4j node ID, CURIE)
    entity_id: Optional[str] = Field(None, description="Unique identifier for the entity, such as a gene ID or drug ID.")
    # Entity type label (aligned or proposed)
    entity_type: Optional[str] = Field(default=None, description="The type of the biomedical entity.")
    # Optional UMLS mapping (CUI and chosen synonym) from embedding search
    mapped_umls_cui: Optional[str] = Field(None, description="UMLS CUI to which the entity was mapped by an Embedding Model.")
    mapped_synonym: Optional[str] = Field(None, description="UMLS synonym to which the entity was mapped by an Embedding Model.")
    # Whether generated by an LLM (vs existing KG entity)
    llm_generated: bool = Field(default=False, description="Indicates whether the entity is generated by LLM.")

    def __str__(self):
        """Return a concise string representation (entity name)."""
        return f"{self.name}"
    
    def __repr__(self):
        """Return a debug-friendly representation with the entity name."""
        return f"BiomedicalEntity(name={self.name})"


class BiomedicalTriplet(BaseModel):
    """
    Pydantic model representing a directed biomedical relation (head -[relation]-> tail),
    with optional supporting evidence and curator-provided evidence.
    """
    # Head (source) entity
    head: BiomedicalEntity = Field(..., description="The head entity of the triplet.")
    # Tail (target) entity
    tail: BiomedicalEntity = Field(..., description="The tail entity of the triplet.")
    # Relation (mechanistic/causal/functional/conceptual)
    relation: str = Field(..., description="The relation type between the head and tail entities.")
    # Evidence backing (e.g., JSON string with paragraph text and article IDs)
    evidences: Optional[str] = Field(None, description="Evidences supporting the triplet, such as a pmc paragraphs and PMCIDs.")
    # Curator-provided evidence (e.g., seed KG evidence)
    curator_evidences: Optional[str] = Field(None, description="Evidences, reported by the curator, supporting the triplet, such as a pmc paragraphs and PMCIDs.")
    # Whether the triplet relation is LLM-generated
    llm_generated: Optional[bool] = Field(None, description="True if triplet is generated by LLM, else False.")

    def __str__(self):
        """Return a concise linearized representation of the triplet."""
        return f"{self.head.name} {self.relation} {self.tail.name}"
    
    def __repr__(self):
        """Return a debug-friendly representation of the triplet."""
        return f"BiomedicalTriplet(head={self.head.name}, relation={self.relation}, tail={self.tail.name})"


class BiomedicalParagraph(Base):
    """
    SQLAlchemy ORM model mapping to a paragraphs table that stores:

    - Unique paragraph ID

 gain access pattern,

    - PMCID (or DOI),
    - Full paragraph text.

    """
    __tablename__ = "paragraphs"

    # Unique identifier of the paragraph (string key to align with upstream systems)
    paragraph_id = Column(String, primary_key=True)
    # PMCID (or DOI) associated with the paragraph
    pmcid = Column(String, nullable=False)
    # Full paragraph text content
    paragraph_text = Column(String, nullable=False)